# security_groups:
#   SecurityGroupBastion:
#     ports:
#       - from: 22
#         to: 22
#       - from: 443
#         to: 443
#   SecurityGroupBackplane:
#     ports:
#       - from: 22
#         to: 22
#       - from: 443
#         to: 443

# advanced_options:
#   rest.action.multi.allow_explicit_index: true

# ebs_options:
#   EBSEnabled: true
#   VolumeSize: 100
#   VolumeType: gp2

# domain_endpoint_options:
#   EnforceHTTPS: true
#   TLSSecurityPolicy: Policy-Min-TLS-1-2-2019-07
